version: '3.8'

services:
  web:
    container_name: "frittenburger"
    image: frittenburger
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      - PYTHONUNBUFFERED=1
    networks:
     - proxy

networks:
  proxy:
    name: "reverse-proxy"
    external: true